_target_: lerobot.common.robot_devices.robots.gello_ur5.gello_ur5Robot
calibration_path: .cache/calibration/gello_ur5.pkl
leader_arms:
  main:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyUSB0 
    motors:
      # name: (index, model)
      shoulder_pan: [1, "xl330-m288"]
      shoulder_lift: [2, "xl330-m288"]
      elbow_flex: [3, "xl330-m288"]
      wrist_1: [4, "xl330-m288"]
      wrist_2: [5, "xl330-m288"]
      wrist_3: [6, "xl330-m288"]
      gripper: [7, "xl330-m077"]
follower_arms: #ur5
  main:
    _target_: lerobot.common.robot_devices.robots.ur.URRobot
    # port: /dev/ttyUSB0 
    # motors:
    #   # name: (index, model)
    #   shoulder_pan: [1, "xl330-m288"]
    #   shoulder_lift: [2, "xl330-m288"]
    #   elbow_flex: [3, "xl330-m288"]
    #   wrist_1: [4, "xl330-m288"]
    #   wrist_2: [5, "xl330-m288"]
    #   wrist_3: [6, "xl330-m288"]
    #   gripper: [7, "xl330-m077"]
cameras:
  head:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 7
    fps: 30
    width: 640
    height: 480
  flan:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 4
    fps: 30
    width: 640
    height: 480
  right:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 6
    fps: 30
    width: 640
    height: 480
